import React,{useState,useEffect,useCallback} from 'react';import {supabase} from '../lib/supabase';import {useAuth} from '../contexts/AuthContext';import {Receipt,Search,Eye,Printer,Download,Trash2,X,Copy} from 'lucide-react';import toast from 'react-hot-toast';
export default function Sales(){const {storeId,canDelete}=useAuth();const [sales,setSales]=useState([]);const [loading,setLoading]=useState(true);const [searchTerm,setSearchTerm]=useState('');const [selectedSale,setSelectedSale]=useState(null);const [showReceipt,setShowReceipt]=useState(false);const [saleItems,setSaleItems]=useState([]);const [companySettings,setCompanySettings]=useState({currency_symbol:'K',company_name:'Store'});
const loadSales=useCallback(async()=>{if(!storeId)return;const {data}=await supabase.from('sales').select('*,customer:customers(name),staff:staff(full_name)').eq('store_id',storeId).eq('returned',false).order('created_at',{ascending:false}).limit(200);setSales(data||[]);setLoading(false);},[storeId]);
useEffect(()=>{if(storeId){loadSales();supabase.from('company_settings').select('currency_symbol,company_name').eq('store_id',storeId).single().then(({data})=>{if(data)setCompanySettings(data);});}},[storeId,loadSales]);
const fetchSaleItems=async(saleId)=>{const {data}=await supabase.from('sale_items').select('*,product:products(name)').eq('sale_id',saleId);setSaleItems(data||[]);};
const handleViewReceipt=async(sale)=>{setSelectedSale(sale);await fetchSaleItems(sale.id);setShowReceipt(true);};
const handleDeleteSale=async(saleId)=>{if(!canDelete)return toast.error('Only admin can delete');if(!window.confirm('Delete permanently?'))return;try{await supabase.from('sale_items').delete().eq('sale_id',saleId);await supabase.from('sales').delete().eq('id',saleId);toast.success('Deleted');loadSales();setShowReceipt(false);}catch(err){toast.error(err.message);}};
const handlePrintReceipt=(sale)=>{const w=window.open('','_blank');w.document.write(generateReceiptHTML(sale));w.document.close();w.print();};
const handleDownloadReceipt=(sale)=>{const blob=new Blob([generateReceiptText(sale)],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`receipt_${sale.invoice_number}.txt`;a.click();};
const handleCopyReceipt=(sale)=>{navigator.clipboard?.writeText(generateReceiptText(sale));toast.success('Copied');};
const generateReceiptText=(sale)=>{const cur=companySettings.currency_symbol;let t=`${companySettings.company_name}\nReceipt #${sale.invoice_number}\n${new Date(sale.created_at).toLocaleString()}\nCashier: ${sale.staff?.full_name}\nCustomer: ${sale.customer?.name||'Walk-in'}\n--------------------------------\n`;saleItems.forEach(i=>t+=`${i.product?.name} x${i.quantity} @ ${cur}${i.unit_price} = ${cur}${i.total}\n`);t+=`--------------------------------\nSubtotal: ${cur}${sale.subtotal?.toFixed(2)}\nVAT: ${cur}${sale.tax_amount?.toFixed(2)}\n${sale.discount_amount>0?`Discount: -${cur}${sale.discount_amount?.toFixed(2)}\n`:''}TOTAL: ${cur}${sale.total_amount?.toFixed(2)}\nThank you!`;return t;};
const generateReceiptHTML=(sale)=>`<html><head><title>Receipt #${sale.invoice_number}</title></head><body style="font-family:monospace;padding:20px;">${generateReceiptText(sale).replace(/\n/g,'<br>')}</body></html>`;
const filtered=sales.filter(s=>s.invoice_number?.toString().includes(searchTerm)||s.customer?.name?.toLowerCase().includes(searchTerm.toLowerCase())||s.staff?.full_name?.toLowerCase().includes(searchTerm.toLowerCase()));
if(loading)return<div className="p-8 text-center">Loading sales...</div>;
return(<div className="p-4 h-full overflow-y-auto"><h1 className="text-2xl font-bold mb-4"><Receipt className="inline mr-2"/>Sales History</h1><div className="mb-4 relative"><Search className="absolute left-3 top-2.5 text-gray-400" size={18}/><input placeholder="Search..." value={searchTerm} onChange={e=>setSearchTerm(e.target.value)} className="w-full pl-10 p-2 border rounded-lg"/></div><div className="bg-white rounded-xl shadow overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 border-b"><tr><th className="p-3">Invoice #</th><th className="p-3">Date</th><th className="p-3">Customer</th><th className="p-3">Cashier</th><th className="p-3 text-right">Total</th><th className="p-3 text-center">Actions</th></tr></thead><tbody>{filtered.map(s=>(<tr key={s.id} className="border-b hover:bg-gray-50"><td className="p-3">{s.invoice_number}</td><td className="p-3">{new Date(s.created_at).toLocaleString()}</td><td className="p-3">{s.customer?.name||'Walk-in'}</td><td className="p-3">{s.staff?.full_name}</td><td className="p-3 text-right">{companySettings.currency_symbol}{s.total_amount?.toFixed(2)}</td><td className="p-3"><div className="flex gap-1 justify-center"><button onClick={()=>handleViewReceipt(s)} className="p-1.5 text-purple-600 hover:bg-purple-50 rounded"><Eye size={18}/></button><button onClick={async()=>{await fetchSaleItems(s.id);handlePrintReceipt(s);}} className="p-1.5 text-gray-600 hover:bg-gray-100 rounded"><Printer size={18}/></button><button onClick={async()=>{await fetchSaleItems(s.id);handleDownloadReceipt(s);}} className="p-1.5 text-green-600 hover:bg-green-50 rounded"><Download size={18}/></button>{canDelete&&<button onClick={()=>handleDeleteSale(s.id)} className="p-1.5 text-red-600 hover:bg-red-50 rounded"><Trash2 size={18}/></button>}</div></td></tr>))}</tbody></table></div></div>{showReceipt&&selectedSale&&(<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"><div className="bg-white rounded-xl w-full max-w-md max-h-[80vh] overflow-auto"><div className="p-4 border-b flex justify-between"><h2>Receipt #{selectedSale.invoice_number}</h2><button onClick={()=>setShowReceipt(false)}><X/></button></div><div className="p-4 font-mono text-sm whitespace-pre-wrap">{generateReceiptText(selectedSale)}</div><div className="p-4 border-t flex justify-end gap-2"><button onClick={()=>handleCopyReceipt(selectedSale)} className="px-3 py-1.5 bg-gray-600 text-white rounded flex items-center gap-1"><Copy size={14}/>Copy</button><button onClick={()=>handlePrintReceipt(selectedSale)} className="px-3 py-1.5 bg-blue-600 text-white rounded"><Printer size={14}/>Print</button><button onClick={()=>handleDownloadReceipt(selectedSale)} className="px-3 py-1.5 bg-green-600 text-white rounded"><Download size={14}/>Download</button></div></div></div>)}</div>);}
